services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ingress-network
    volumes:
      - ./config:/etc/influxdb2
      - ${DATA}/influx/data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    labels:
      - "homepage.group=Dashboard"
      - "homepage.name=Influxdb"
      - "homepage.icon=influxdb"
      - "homepage.href=http://basserver:8086"


networks:
  ingress-network:
    external: true
