services:
  homepage:
    image: ghcr.io/vanbassum/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - ingress-network
    ports:
      - "80:8080"
    volumes:
      - ${DATA}/homepage/data:/data

networks:
  ingress-network:
    external: true
