services:
  telegraf:
    image: telegraf:1.31.0-alpine
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - ingress-network

networks:
  ingress-network:
    external: true
