services:
  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${PUID}:${PGID}"
    networks:
      - ingress-network
    depends_on:
      - postgres
      - redis
    volumes:
      - ${DATA}/outline/data:/var/lib/outline/data
    environment:
      # Basic
      - NODE_ENV=production
      - URL=http://basserver.local:3002
      - PORT=3000
      - FORCE_HTTPS=false

      # Security (CHANGE THESE)
      - SECRET_KEY=c23bbba90c436230705383b28a23e448f17fe8dbeece0582f86bb221361d664a
      - UTILS_SECRET=c23bbba90c436230705383b28a23e448f17fe8dbeece0582f86bb221361d664a

      # Database
      - DATABASE_URL=postgres://outline:outline@postgres:5432/outline
      - PGSSLMODE=disable

      # Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_COLLABORATION_URL=redis://redis:6379

      # Auth (simple local auth enabled)
      - ENABLED_AUTH_STRATEGIES=local


    ports:
      - "3002:3000"

  postgres:
    image: postgres:15
    container_name: outline-postgres
    restart: unless-stopped
    networks:
      - ingress-network
    volumes:
      - ${DATA}/outline/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=outline
      - POSTGRES_PASSWORD=outline
      - POSTGRES_DB=outline

  redis:
    image: redis:7
    container_name: outline-redis
    restart: unless-stopped
    networks:
      - ingress-network
    volumes:
      - ${DATA}/outline/redis:/data

networks:
  ingress-network:
    external: true
