services:
  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - ingress-network

networks:
  ingress-network:
    external: true
