services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${DATA}/pocketbase:/pb_data
    networks:
      - ingress-network

networks:
  ingress-network:
    external: true
