services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:0.22.21
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${DATA}/pocketbase:/pb/pb_data
    networks:
      - ingress-network

networks:
  ingress-network:
    external: true
